### ISSUE TITLE
Grammar Errors

### ISSUE THREAD

**Issue by mjsolidarios** [jayxce/jaycxe#1]
> Please fix these mistakes Jaycee. Thanks!

I am Jaycee **,** a student <strike>in</strike> **at** West Visayas State University, currently studying **Bachelor of Science in** Information Technology <strike>and Mastering</strike> <strike>Software Developement</strike>  **major in software development** . I am what they call a jack of all trades **,** master of <strike>non</strike> **none**. I play games, practice photography and I also do editing, again I am not that good. I have been <strike>fastinated</strike> fascinated by computers since I was young but I had no idea how to <strike>start up</strike> **begin with**. So here I am now studying my dream <strike>coarse</strike> **course** and will do my best to program a game and other software <strike>s</strike>.

**Comment by jayxce** [comment]
on it sir

**Comment by mjsolidarios** [comment]
Aight! Thanks again!
